# Header
menu:
  Home: /
  Archives: /archives
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- recent_posts
- archive
- category
- tag
- tagcloud

# Miscellaneous
google_analytics: UA-35739428-1
favicon: /favicon.png
twitter: smerrell
google_plus:
fb_admins:
fb_app_id:
